ProyectoCultura/ProyectoCultura/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.artistas.urls', namespace="artista"),),
    url(r'^', include('apps.eventos.urls', namespace="evento"),),
    url(r'^', include('apps.home.urls', namespace="home")),
    url(r'^', include('apps.adm.urls', namespace="adm")),
    url(r'^login/$', login, {'template_name': 'usuarios/login.html'},name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout',{'next_page': '/'}, name="logout"),
    url(r'^$', 'django.contrib.auth.views.login',{'next_page': 'home/base_user.html'}),
    #url(r'^logout/',logout_then_login, name="logout"),
)	+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoCultura/apps/adm/urls.py
from django.contrib import admin
from django.conf.urls import patterns, url

from .views import ListarNotificacion,AutorizacionUsuario, AutorizacionEvento


urlpatterns = patterns('',

	url(r'^adm/notificacion/$', ListarNotificacion.as_view(), name="notificacion"),
	url(r'^autorizar/user/(?P<pk>\d+)/$', AutorizacionUsuario.as_view(), name='autorizacion_artista'),
	url(r'^autorizar/evento/(?P<pk>\d+)/$', AutorizacionEvento.as_view(), name='autorizacion_evento'),
)

ProyectoCultura/apps/artistas/urls.py
from django.conf.urls import patterns, url
from .views import RegistroArtista, PerfilArtista, EditarArtista, ListarArtista, PerfilArtista

urlpatterns = patterns('',
	 url(r'^registro/artista/$', RegistroArtista.as_view(), name="registro"),
     url(r'^usuario/(?P<pk>\d+)/$', PerfilArtista.as_view(), name="perfil"),
     url(r'^editar/(?P<pk>\d+)/$', EditarArtista.as_view(), name='editar'),
     url(r'^listar/artista/$', ListarArtista.as_view(), name='listar'),
     url(r'^perfil/artista/$', PerfilArtista.as_view(), name='perfil_usuario'),
     
)

ProyectoCultura/apps/eventos/urls.py
from django.conf.urls import  patterns, url

from .views import ListarEvento, RegistrarEvento, EditarEvento, ListarEventoUser


urlpatterns = patterns('',
	
    url(r'^listar/evento/$', ListarEvento.as_view(), name='listar'),
    url(r'^registro/evento/$', RegistrarEvento.as_view(), name='crear'),
    url(r'^editar/evento/(?P<pk>\d+)/$',EditarEvento.as_view(), name='editar'),
    url(r'^listar/evento/user/$', ListarEventoUser.as_view(), name='listar_user'),
)

ProyectoCultura/apps/home/urls.py
from django.conf.urls import patterns, include, url
from .views import IndexView, IndexViewUser

urlpatterns = patterns('',
	url(r'^$', IndexView.as_view(), name="index"),
	url(r'^user/$', IndexViewUser.as_view(), name="home_user"),

)

ProyectoCultura/templates/base/base_principal.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

       <title>Casa de la cultura Quetzaltenango</title>
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css'%}" rel="stylesheet">
	<link href="{% static 'css/main.css'%}" rel="stylesheet">
	<link href="{% static 'css/animate.css'%}" rel="stylesheet">
	<link href="{% static 'css/responsive.css'%}" rel="stylesheet">
	<link href="{% static 'css/evento.css'%}" rel="stylesheet">

    <!--[if lt IE 9]>
	    <script src="js/html5shiv.js"></script>
	    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="img/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{static 'img/ico/apple-touch-icon-144-precomposed.png'}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'img/ico/apple-touch-icon-114-precomposed.png'%}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'img/ico/apple-touch-icon-72-precomposed.png'%}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'img/ico/apple-touch-icon-57-precomposed.png'%}">
</head><!--/head-->

<body>

<!--<audio controls autoplay>
  <source src="{%static 'img/luna.mp3'%}" type="audio/mpeg">
  Your browser does not support the audio element.
</audio>-->

{% block navbar%}
	<header id="header" role="banner">
		<div class="main-nav">
			<div class="container">
				<div class="header-top">
					<div class="pull-right social-icons">
						<a href="https://www.facebook.com/pages/Casa-de-la-Cultura-Quetzaltenango/491201117581960?fref=ts"><i class="fa fa-twitter"></i></a>
						<a href="#"><i class="fa fa-facebook"></i></a>
						<a href="#"><i class="fa fa-google-plus"></i></a>
						<a href="#"><i class="fa fa-youtube"></i></a>
					</div>
				</div>
		        <div class="row">
		            <div class="navbar-header">
		                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		                    <span class="sr-only">Navegacion</span>
		                    <span class="icon-bar"></span>
		                    <span class="icon-bar"></span>
		                    <span class="icon-bar"></span>
		                </button>
		                <a class="navbar-brand" href="{%url 'home:index'%}">
		                	<img class="img-responsive" src="{% static 'img/logo.png'%}" alt="logo">
		                </a>
		            </div>
		             <div class="collapse navbar-collapse">
		                <ul class="nav navbar-nav navbar-right">
		                    <li><a class="no-scroll active" href="{%url 'home:index'%}" >Inicio</a></li>
		                  <li><a class="no-scroll" href="{%url 'evento:listar'%}" >Eventos</a></li>
		                 <li><a class="no-scroll" href="{%url 'artista:listar'%}" >Artistas</a></li>


		                     {% if user.is_authenticated %}
		                     <li><a class="no-scroll" href="{%url 'home:home_user'%}" >Control</a></li>
		                     {%else%}
                             <li><a class="no-scroll" href="{%url 'artista:registro'%}" >Registro</a></li>
		                     <li><a class="no-scroll" href="{%url 'login'%}" >Login</a></li>

		                     {%endif%}



		                     <li class="scroll"><a href="#contact">Contacto</a></li>

		                </ul>
		            </div>
		        </div>
	        </div>
        </div>
    </header>
{%endblock%}



	<section id="home">
		<div id="main-slider" class="carousel slide" data-ride="carousel">
			<ol class="carousel-indicators">
				<li data-target="#main-slider" data-slide-to="0" class="active"></li>
				<li data-target="#main-slider" data-slide-to="1"></li>
				<li data-target="#main-slider" data-slide-to="2"></li>
			</ol>
			<div class="carousel-inner">

		{% if eventos%}
				<div class="item active">
					<img class="img-responsive" src="{% static 'img/slider/bg1.jpg'%}" alt="slider">
					<div class="carousel-caption">
						<h2>{{evento.titulo}}</h2>
						<h4>{{evento.descripcion}}</h4>

					</div>
				</div>

		{%for evento in eventos%}

				<div class="item">
					<img class="img-responsive" src="{% static 'img/slider/bg2.jpg'%}" alt="slider">
					<div class="carousel-caption">
						<h2>{{evento.titulo}} </h2>
						<h4>{{evento.descripcion}}</h4>
					<!--	<a href="#">Ver mas<i class="fa fa-angle-right"></i></a>-->

					</div>
				</div>

		{%endfor%}

		{% else%}


				<div class="item active">
					<img class="img-responsive" src="{% static 'img/slider/bg1.jpg'%}" alt="slider">
					<div class="carousel-caption">
						<h2>Concierto musical </h2>
						<h4>Concierto de la orquesta de Quetzaltenango</h4>
						<a href="#">Ver mas<i class="fa fa-angle-right"></i></a>
					</div>
				</div>
				<div class="item">
					<img class="img-responsive" src="{% static 'img/slider/bg2.jpg'%}" alt="slider">
					<div class="carousel-caption">
						<h2>Obra de teatro </h2>
						<h4>El grupo Js presentara su obra de teatro</h4>
						<a href="#">Ver mas<i class="fa fa-angle-right"></i></a>
					</div>
				</div>
				<div class="item">
					<img class="img-responsive" src="{% static 'img/slider/bg3.jpg'%}" alt="slider">
					<div class="carousel-caption">
						<h2>Baile Folklorico </h2>
						<h4>Convite navideño del grupo de la casa de la cultura</h4>
						<a href="#contact" >Ver mas <i class="fa fa-angle-right"></i></a>
					</div>
				</div>

		{% endif%}
			</div>

		</div>
	</section>
{%block content%}

{%endblock%}

	<section id="contact">

		<div class="contact-section">
			<div class="ear-piece">
				<img class="img-responsive" src="{%static 'img/ear-piece.png'%}" alt="">
			</div>
			<div class="container">
				<div class="row">
					<div class="col-sm-3 col-sm-offset-4">
						<div class="contact-text">
							<h3>Contacto</h3>
							<address>
								E-mail: casadelaculturaquetzaltenango@gmail.com<br>
								Tel:  (502) 456 7890<br>
							</address>
						</div>
						<div class="contact-address">
							<h3>Direccion</h3>
							<address>
								Parque Central,<br>
								Quetzaltenango,<br>
								Guatemala
							</address>
						</div>
					</div>
					<div class="col-sm-5">
						<div id="contact-section">
							<h3>Enviar Mensaje</h3>
					    	<div class="status alert alert-success" style="display: none"></div>
					    	<form id="main-contact-form" class="contact-form" name="contact-form" method="post" action="http://stereoamistad.com/send.php">
					            <div class="form-group">
					                <input type="text" name="name" class="form-control" required="required" placeholder="Nombre">
					            </div>
					            <div class="form-group">
					                <input type="email" name="email" class="form-control" required="required" placeholder="Email">
					            </div>
					            <div class="form-group">
					                <textarea name="message" id="message" required="required" class="form-control" rows="4" placeholder="Aqui su mensaje"></textarea>
					            </div>
					            <div class="form-group">
					                <button type="submit" class="btn btn-primary pull-right">Enviar</button>
					            </div>
					        </form>
					    </div>
					</div>
				</div>
			</div>
		</div>
	</section>
    <!--/#contact-->


    <footer id="footer">
        <div class="container">
            <div class="text-center">
                <p> Todos los derechos reservados  &copy;2016<a target="_blank" href="index.html"> Casa de la cultura </a> Quetzaltenango <br> Diseñado por <a target="_blank" href="#">Grupo 2 Ingenieria de Software</a></p>
            </div>
        </div>
    </footer>

	<script type="text/javascript" src="{% static 'js/eventos.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
  	<script type="text/javascript" src="{% static 'js/gmaps.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/smoothscroll.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.parallax.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/coundown-timer.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.scrollTo.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.nav.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/main.js'%}"></script>
</body>
</html>

ProyectoCultura/templates/base/base_user.html
{%load staticfiles%}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
   {%block title%} <title>Casa de la cultura - Administracion</title> {%endblock%}
    <!-- BOOTSTRAP CORE STYLE  -->
    <link href="{%static 'css/bootstrap.css'%}" rel="stylesheet" />
    <!-- FONT AWESOME ICONS  -->
    <link href="{%static 'css/font-awesome.css'%}" rel="stylesheet" />
    <link href="{%static 'css/evento.css'%}" rel="stylesheet" />
    <!-- CUSTOM STYLE  -->
    <link href="{%static 'css/style.css'%}" rel="stylesheet" />
    <link rel="shortcut icon" href="{%static 'img/favicon.png'%}">
</head>
<body>
    <header>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                   <strong>Email: </strong>grupo2@hotmail.com
                    &nbsp;&nbsp;
                    <strong>Soporte tecnico: </strong>+502 5429-8280
                </div>

            </div>
        </div>
    </header>
    <!-- HEADER END-->
    <div class="navbar navbar-inverse set-radius-zero">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{%url 'home:home_user'%}">

                    <img src="{%static 'img/logo.png'%}" />
                </a>

            </div>

            <div class="left-div">
                <div class="user-settings-wrapper">
                    <ul class="nav">

                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
                                <span class="glyphicon glyphicon-user" style="font-size: 25px;"></span>
                            </a>
                            <div class="dropdown-menu dropdown-settings">
                                <div class="media">

                                    <div class="media-body">
                                        {% if user.is_staff%}
                                        <h4 class="media-heading">Administrador</h4>

                                        {%else%}
                                        <h4 class="media-heading">{{user.first_name}}</h4>

                                        {%endif%}

                                    </div>
                                </div>
                                <hr />
                                 <a href="{%url 'logout'%}" class="btn btn-danger btn-sm">Cerrar Sesion</a>

                            </div>
                        </li>


                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- LOGO HEADER END-->




{% if user.is_authenticated %}
{% if user.is_staff%}

<section class="menu-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="navbar-collapse collapse ">
                        <ul id="menu-top" class="nav navbar-nav navbar-right">
                            <li><a href="{%url 'home:home_user'%}">Escritorio</a></li>
                            <li><a href="{%url 'evento:listar_user'%}">Evento</a></li>
                            <li><a href="{%url 'evento:crear' %}">Crear evento</a></li>
                            <li><a href="#">Crear capsula</a></li>
                            <li><a href="{%url 'adm:notificacion'%}">Notificaciones</a></li>
                            <li><a href="{%url 'home:index'%}">Ir al sitio</a></li>

                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </section>

{%else%}

<section class="menu-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="navbar-collapse collapse ">
                        <ul id="menu-top" class="nav navbar-nav navbar-right">
                            <li><a href="#">Escritorio</a></li>
                            <li><a href="{%url 'evento:listar_user'%}">Evento</a></li>
                            <li><a href="{%url 'evento:crear' %}">Crear evento</a></li>
                            <li><a href="{%url 'artista:editar' user.id%}">Perfil</a></li>
                            <li><a href="{%url 'home:index'%}">Ir al sitio</a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
</section>

{%endif%}
{%else%}

{%endif%}

{%block content%}



{%endblock%}




     <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                       &copy; 2016 Grupo 2 | Por : <a href="#" target="_blank">Ingenieria de software</a>
                </div>

            </div>
        </div>
    </footer>
    <!-- FOOTER SECTION END-->
    <!-- JAVASCRIPT AT THE BOTTOM TO REDUCE THE LOADING TIME  -->
    <!-- CORE JQUERY SCRIPTS -->
    <script src="{%static 'js/jquery-1.11.1.js'%}"></script>
    <!-- BOOTSTRAP SCRIPTS  -->
    <script src="{%static 'js/bootstrap.js'%}"></script>
</body>
</html>