ProyectoCultura/ProyectoCultura/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.artistas.urls', namespace="artista"),),
    url(r'^', include('apps.eventos.urls', namespace="evento"),),
    url(r'^', include('apps.home.urls', namespace="home")),
    url(r'^', include('apps.adm.urls', namespace="adm")),
    url(r'^login/$', login, {'template_name': 'usuarios/login.html'},name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout',{'next_page': '/'}, name="logout"),
    url(r'^$', 'django.contrib.auth.views.login',{'next_page': 'home/base_user.html'}),
    #url(r'^logout/',logout_then_login, name="logout"),
)	+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoCultura/apps/eventos/urls.py
from django.conf.urls import  patterns, url

from .views import ListarEvento, RegistrarEvento, EditarEvento, ListarEventoUser


urlpatterns = patterns('',
	
    url(r'^listar/evento/$', ListarEvento.as_view(), name='listar'),
    url(r'^registro/evento/$', RegistrarEvento.as_view(), name='crear'),
    url(r'^editar/evento/(?P<pk>\d+)/$',EditarEvento.as_view(), name='editar'),
    url(r'^listar/evento/user/$', ListarEventoUser.as_view(), name='listar_user'),
)

ProyectoCultura/apps/eventos/models.py
from django.db import models
from django.contrib.auth.models import User

from apps.artistas.models import Artista, Categoria
# Create your models here.


class Tamanio(models.Model):
    descripcion = models.CharField(max_length=10)


class Evento(models.Model):
    user = models.ForeignKey(User,null=False, blank=False, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=45)
    categoria = models.ForeignKey(Categoria, null=True, blank=True, on_delete=models.CASCADE)
    direccion = models.CharField(max_length=70)
    horario = models.DateTimeField(null=True, blank=True)
    autorizado = models.BooleanField(default=False)
    tamanio = models.ForeignKey(Tamanio, null=True, blank=True, on_delete=models.CASCADE)
    descripcion = models.TextField(max_length=200)
    imagen = models.ImageField(upload_to='img/', null=True, blank=True)


class Resenia(models.Model):
	user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
	nombre = models.CharField(max_length=35, null=True, blank=True)
	contenido = models.TextField(max_length=250)
	evento = models.ForeignKey(Evento, null=False, blank=False, on_delete=models.CASCADE)

ProyectoCultura/apps/eventos/forms.py
from django import forms
from .models import Evento


class EventoForm(forms.ModelForm):
    class Meta:
        model = Evento

        fields = [
        		'titulo',
        		'categoria',
        		'direccion',
        		'imagen',
        		'descripcion',
        		'horario',


        ]

ProyectoCultura/apps/eventos/views.py
from django.shortcuts import render
from django.http import  HttpResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from braces.views import LoginRequiredMixin

from .models import Evento
from .forms import EventoForm
from apps.adm.models import NotificacionEvento

# Create your views here.

def index(request):
    return render(request,'evento/evento.html')


class ListarEvento(ListView):
    model = Evento
    template_name = 'eventos/listar.html'
    queryset = Evento.objects.filter(autorizado=True)

    def get_context_data(self, **kwargs):
        context = super(ListarEvento, self).get_context_data(**kwargs)
        context['eventos'] = Evento.objects.filter(autorizado=True)[:3]
        return context


class ListarEventoUser(ListView):
    model = Evento
    template_name = 'eventos/listar_form.html'
    def get_context_data(self, **kwargs):
        context = super(ListarEventoUser, self).get_context_data(**kwargs)
        context['evento'] = Evento.objects.filter(user=self.request.user)
        return context



class RegistrarEvento(LoginRequiredMixin ,CreateView):
    model = Evento
    form_class = EventoForm
    template_name = 'eventos/registro_form.html'
    login_url = '/'
    success_url = '/'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST, self.request.FILES)
        if form.is_valid():
            evento = form.save(commit=False)
            evento.user = request.user
            if request.user.is_superuser:
                evento.autorizado=True
                evento.save()
            else:
                evento.save()
                noti = NotificacionEvento.objects.create(evento=evento)
                noti.save()
            return render(request, 'home/index_user.html')
        else:
            return self.render_to_response(self.get_context_data(form=form))



class EditarEvento(LoginRequiredMixin ,UpdateView):
    model = Evento
    form_class =EventoForm
    context_object_name="evento"
    template_name= 'eventos/editar_form.html'
    success_url = '/'
    login_url= '/'

class EventoDelete(DeleteView):
    model = Evento
    template_name='evento/evento_delete.html'
    success_url = '/'

ProyectoCultura/templates/eventos/editar_form.html
{%extends 'base/base_user.html'%}

    <!-- MENU SECTION END-->
{%block content%}

 <!-- MENU SECTION END-->
 <div class="content-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h4 class="page-head-line">Modificacion de evento</h4>
                        <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="text-center">


      </div>
    </div>
    <!-- edit form column -->
    <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
      <div class="alert alert-info alert-dismissable">
        <a class="panel-close close" data-dismiss="alert">×</a>
        <i class="fa fa-coffee"></i>
        <strong>Llenar todos los campos</strong>.
      </div>
      <h3>Evento</h3>
      <form class="form-horizontal" role="form" method="POST" enctype='multipart/form-data'>
      {%csrf_token%}

        <div class="form-group">
          <label class="col-lg-3 control-label">Titulo:</label>
          <div class="col-lg-8">
            <input class="form-control" value="{{evento.titulo}}" type="text" name="titulo">
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label">Horario:</label>
          <div class="col-lg-8">
            <input class="form-control" value="{{evento.horario| date:'Y-m-d H:i'}}" type="text" name="horario">
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label">Direccion:</label>
          <div class="col-lg-8">
            <input class="form-control" value="{{evento.direccion}}" type="text" name="direccion">
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label">Imagen:</label>
          <div class="col-lg-8">
            <input class="form-control" value="" type="file" name="imagen">
          </div>
        </div>



<script type="text/javascript">
    $(".form_datetime").datetimepicker({
        format: "dd MM yyyy - hh:ii",
        autoclose: true,
        todayBtn: true,
        pickerPosition: "bottom-left"
    });
</script>

          <div class="form-group">
          <label class="col-lg-3 control-label">Descripcion:</label>
          <div class="col-lg-8">
            <textarea class="form-control" value="{{evento.descripcion}}" type="text" name="descripcion">{{evento.descripcion}}
            </textarea>
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">Categoria:</label>
          <div class="col-lg-8">
            <div class="ui-select">
              {{form.categoria}}
            </div>
          </div>
        </div>

        <div class="form-group">
          <label class="col-md-3 control-label"></label>
          <div class="col-md-8">
            <input class="btn btn-primary" value="Guardar cambios" type="submit">
            <span></span>
            <input class="btn btn-default" value="Cancelar" type="reset">
          </div>
        </div>
      </form>
    </div>

                </div>

            </div>
            <div class="row">
                <div class="col-md-12">



                </div>

            </div>
        </div>
    </div>


{%endblock%}

ProyectoCultura/templates/eventos/listar.html
{% extends 'base/base_principal.html'%}


{% block content%}
	<section id="event">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 col-md-9">
					<div id="event-carousel" class="carousel slide" data-interval="false">
						<h2 class="heading">Listado de eventos</h2>


							<div class="well well-sm">

        <div class="btn-group">
            <a href="#" id="list" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-th-list">
            </span>Lista</a> <a href="#" id="grid" class="btn btn-default btn-sm"><span
                class="glyphicon glyphicon-th"></span>Cuadrado</a>
        </div>
    </div>

    <div id="products" class="row list-group">

        {% if object_list%}
        {% for evento in object_list%}
        <div class="item  col-xs-4 col-lg-4">
            <div class="thumbnail">
                <img class="group list-group-image" src="{{evento.imagen.url}}" alt="" />
                <div class="caption">
                    <h4 class="group inner list-group-item-heading">
                        {{evento.titulo}}</h4>
                    <p class="group inner list-group-item-text">
                        Fecha: {{evento.horario}}</p>
                    <p class="group inner list-group-item-text">
                        {{evento.descripcion}}</p>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">

                        </div>

                    </div>
                </div>
            </div>
        </div>
        {%endfor%}
        {%else%}
        <h1> No hay eventos <h1>
        {%endif%}






    </div>





					</div>
				</div>
			</div>
		</div>
	</section><!--/#event-->

{% endblock %}

ProyectoCultura/templates/eventos/listar_form.html
{%extends 'base/base_user.html'%}

    <!-- MENU SECTION END-->
{%block content%}

    <section id="twitter">
        <div id="twitter-feed" class="carousel slide" data-interval="false">
            <div class="row">
            <div class="[ col-xs-12 col-sm-offset-2 col-sm-8 ]">



            {% if evento%}
            {% for evento in evento%}
            <ul class="event-list">
                    <li>
                        <time datetime="2014-07-20">
                            <span class="day">{{evento.horario.date|date:'d'}}</span>
                            <span class="month">{{evento.horario.date|date:'M'}}</span>
                            <span class="year">{{evento.horario.date|date:'Y'}}</span>

                        </time>
                        <img alt="Independence Day" src="{{evento.imagen.url}}" />
                        <div class="info">
                            <h2 class="title">{{evento.titulo}}</h2>
                            <p class="desc">{{evento.descripcion}}</p>
                            <a href="{%url 'evento:editar' evento.id %}" class="btn btn-primary">Editar</a>

                        </div>
                    </li>

                </ul>

            {%endfor%}

            {%else%}
            <h1>No eventos creados</h1>
            {%endif%}

            </div>
        </div>
        </div>
    </section><!--/#twitter-feed-->


{%endblock%}

ProyectoCultura/templates/eventos/perfil_form.html
{%extends 'base/base_user.html'%}

    <!-- MENU SECTION END-->
{%block content%}
    <div class="content-wrapper">
        <div class="container">
            <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-head-line">Evento</h1>
                    </div>
                </div>
                <div class="row">
                <div class="col-md-6">
               
               
            </div>
                <div class="row">
                
                <
                     <!--  End  Bordered Table  -->
                </div>
            </div>
                <div class="row">
                <div class="col-md-6">
                     <!--    Hover Rows  -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Hover Rows
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>First Name</th>
                                            <th>Last Name</th>
                                            <th>Username</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1</td>
                                            <td>Mark</td>
                                            <td>Otto</td>
                                            <td>@mdo</td>
                                        </tr>
                                        <tr>
                                            <td>2</td>
                                            <td>Jacob</td>
                                            <td>Thornton</td>
                                            <td>@fat</td>
                                        </tr>
                                        <tr>
                                            <td>3</td>
                                            <td>Larry</td>
                                            <td>the Bird</td>
                                            <td>@twitter</td>
                                        </tr>
                                        <tr>
                                            <td>4</td>
                                            <td>Larry</td>
                                            <td>the Bird</td>
                                            <td>@twitter</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- End  Hover Rows  -->
                </div>
                <div class="col-md-6">
                     <!--    Context Classes  -->
                    <div class="panel panel-default">
                       
                        <div class="panel-heading">
                            Context Classes
                        </div>
                        
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>First Name</th>
                                            <th>Last Name</th>
                                            <th>Username</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr class="success">
                                            <td>1</td>
                                            <td>Mark</td>
                                            <td>Otto</td>
                                            <td>@mdo</td>
                                        </tr>
                                        <tr class="info">
                                            <td>2</td>
                                            <td>Jacob</td>
                                            <td>Thornton</td>
                                            <td>@fat</td>
                                        </tr>
                                        <tr class="warning">
                                            <td>3</td>
                                            <td>Larry</td>
                                            <td>the Bird</td>
                                            <td>@twitter</td>
                                        </tr>
                                        <tr class="danger">
                                            <td>4</td>
                                            <td>John</td>
                                            <td>Smith</td>
                                            <td>@jsmith</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!--  end  Context Classes  -->
                </div>
            </div>

        </div>
    </div>

{%endblock%}

ProyectoCultura/templates/eventos/registro_form.html
{%extends 'base/base_user.html'%}

    <!-- MENU SECTION END-->
{%block content%}

 <!-- MENU SECTION END-->
 <div class="content-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h4 class="page-head-line">Creacion de evento</h4>
                        <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="text-center">


      </div>
    </div>
    <!-- edit form column -->
    <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
      <div class="alert alert-info alert-dismissable">
        <a class="panel-close close" data-dismiss="alert">×</a>
        <i class="fa fa-coffee"></i>
        <strong>Llenar todos los campos</strong>.
      </div>
      <h3>Evento</h3>
      <form class="form-horizontal" role="form" method="POST" enctype='multipart/form-data'>
      {%csrf_token%}
        <div class="form-group">
          <label class="col-lg-3 control-label">Titulo:</label>
          <div class="col-lg-8">
            <input class="form-control" value="" type="text" name="titulo">
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label">Horario:</label>
          <div class="col-lg-8">
            <input class="form-control" value="2016-12-08 10:00" type="text" name="horario">
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label">Direccion:</label>
          <div class="col-lg-8">
            <input class="form-control" value="" type="text" name="direccion">
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label">Imagen:</label>
          <div class="col-lg-8">
            <input class="form-control" value="" type="file" name="imagen">
          </div>
        </div>



<script type="text/javascript">
    $(".form_datetime").datetimepicker({
        format: "dd MM yyyy - hh:ii",
        autoclose: true,
        todayBtn: true,
        pickerPosition: "bottom-left"
    });
</script>

          <div class="form-group">
          <label class="col-lg-3 control-label">Descripcion:</label>
          <div class="col-lg-8">
            <textarea class="form-control" value="" type="text" name="descripcion">
            </textarea>
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">Categoria:</label>
          <div class="col-lg-8">
            <div class="ui-select">
                {{form.categoria}}
            </div>
          </div>
        </div>

        <div class="form-group">
          <label class="col-md-3 control-label"></label>
          <div class="col-md-8">
            <input class="btn btn-primary" value="Guardar cambios" type="submit">
            <span></span>
            <input class="btn btn-default" value="Cancelar" type="reset">
          </div>
        </div>
      </form>
    </div>

                </div>

            </div>
            <div class="row">
                <div class="col-md-12">



                </div>

            </div>
        </div>
    </div>


{%endblock%}





<!--<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
</head>

<body>

	<h1> Registro Evento </h1>
	<form method='POST' action='' enctype='multipart/form-data'>
		{%csrf_token%}
		<p> <label>Titulo:</label>
		{{form.titulo}}</p>

		<p> <label>Categoria:</label>
		{{form.categoria}}</p>

		<p> <label>Direccion:</label>
		{{form.direccion}}</p>

		<p> <label>Horario:</label>
		{{form.horario}}</p>

		<p> <label>Descripcion:</label>
		{{form.descripcion}}</p>


		{{form.errors.as_data}}
		<p><input type="submit" value="Guardar"></p>
	</form>
</body>

</html>

-->