ProyectoCultura/ProyectoCultura/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.artistas.urls', namespace="artista"),),
    url(r'^', include('apps.eventos.urls', namespace="evento"),),
    url(r'^', include('apps.home.urls', namespace="home")),
    url(r'^', include('apps.adm.urls', namespace="adm")),
    url(r'^login/$', login, {'template_name': 'usuarios/login.html'},name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout',{'next_page': '/'}, name="logout"),
    url(r'^$', 'django.contrib.auth.views.login',{'next_page': 'home/base_user.html'}),
    #url(r'^logout/',logout_then_login, name="logout"),
)	+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoCultura/apps/adm/urls.py
from django.contrib import admin
from django.conf.urls import patterns, url

from .views import ListarNotificacion,AutorizacionUsuario, AutorizacionEvento


urlpatterns = patterns('',

	url(r'^adm/notificacion/$', ListarNotificacion.as_view(), name="notificacion"),
	url(r'^autorizar/user/(?P<pk>\d+)/$', AutorizacionUsuario.as_view(), name='autorizacion_artista'),
	url(r'^autorizar/evento/(?P<pk>\d+)/$', AutorizacionEvento.as_view(), name='autorizacion_evento'),
)

ProyectoCultura/apps/adm/models.py
from django.db import models
from django.contrib.auth.models import User

from apps.eventos.models import Evento

# Create your models here.

class NotificacionBase(models.Model):
	verificado = models.BooleanField(default=False)


class NotificacionArtista(NotificacionBase):
	artista = models.OneToOneField(User, unique=True)



class NotificacionEvento(NotificacionBase):
	evento = models.OneToOneField(Evento, unique=True)


class Capsula(models.Model):
	titulo = models.CharField(max_length=10,null=False, blank=False)
	contenido = models.TextField(max_length=255, null=False)
	fecha = models.DateField()

ProyectoCultura/apps/adm/views.py
from django.shortcuts import render
from django.views.generic import UpdateView, ListView, DetailView
from django.http import HttpResponse
from django.contrib.auth.models import User

from .models import NotificacionArtista, NotificacionEvento
from apps.artistas.models import Artista
from apps.eventos.models import Evento
# Create your views here.


class ListarNotificacion(ListView):
	#General
	model = NotificacionArtista
	template_name = 'usuarios/adm/notificacion.html'
	queryset = NotificacionArtista.objects.filter(verificado=False)
	context_object_name = 'artistas'
	

	def get_context_data(self, **kwargs):
		context = super(ListarNotificacion, self).get_context_data(**kwargs)
		context['eventos'] = NotificacionEvento.objects.filter(verificado=False)
		return context

class AutorizacionUsuario(UpdateView):
	model = User
	second_model = Artista
	template_name = 'usuarios/adm/autorizacionArtista.html'
	context_object_name = 'usuario'

	def post(self, request, *args, **kwargs):
		self.object = self.get_object
		pk = kwargs['pk']
		noti = NotificacionArtista.objects.get(artista = pk)
		artista = Artista.objects.get(user = pk)
		artista.autorizado = True
		noti.verificado = True
		noti.save()
		artista.save()
		return render(request, 'home/index_user.html')


class AutorizacionEvento(UpdateView):
	model = Evento
	template_name = 'usuarios/adm/autorizacionEvento.html'
	context_object_name = 'evento'

	def post(self, request, *args, **kwargs):
		self.object = self.get_object
		pk = kwargs['pk']
		noti = NotificacionEvento.objects.get(evento = pk)
		evento = Evento.objects.get(id = pk)
		evento.autorizado = True
		noti.verificado = True
		noti.save()
		evento.save()
		return render(request, 'home/index_user.html')

ProyectoCultura/templates/usuarios/adm/autorizacionArtista.html
{%extends 'base/base_user.html'%}

{%block content%}

    <!-- MENU SECTION END-->
    <div class="content-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h4 class="page-head-line">Usuario {{usuario.username}}</h4>
                        <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="text-center">
        <img src="{{usuario.artista.imagen.url}}" class="avatar img-circle img-thumbnail" alt="avatar">
      </div>
    </div>
    <!-- edit form column -->
    <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
      <div class="alert alert-info alert-dismissable">
        <a class="panel-close close" data-dismiss="alert">×</a>
        <i class="fa fa-coffee"></i>
      </div>
      <h3>Informacion personal</h3>
      <form class="form-horizontal" role="form" method="POST">
      {%csrf_token%}
        <div class="form-group">
          <label class="col-lg-3 control-label">Nombre:</label>
          <div class="col-lg-8">
            <input class="form-control" value="{{usuario.first_name}}" type="text" disabled>
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">Apellido:</label>
          <div class="col-lg-8">
            <input class="form-control" value="{{usuario.last_name}}" type="text" disabled>
          </div>
        </div>


<script type="text/javascript">
    $(".form_datetime").datetimepicker({
        format: "dd MM yyyy - hh:ii",
        autoclose: true,
        todayBtn: true,
        pickerPosition: "bottom-left"
    });
</script>

               <div class="form-group">
          <label class="col-lg-3 control-label">Email:</label>
          <div class="col-lg-8">
            <input class="form-control" value="{{usuario.email}}" type="text" disabled>
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-3 control-label">Telefono:</label>
          <div class="col-lg-8">
            <input class="form-control" value="{{usuario.artista.telefono}}" type="text" disabled>
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label">Usuario:</label>
          <div class="col-md-8">
            <input class="form-control" value="{{usuario.username}}" type="text" disabled>
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-3 control-label"></label>
          <div class="col-md-8">


            <input class="btn btn-primary" value="Autorizar" type="submit">

            <span></span>

          </div>
        </div>
      </form>
    </div>

                </div>

            </div>
            <div class="row">
                <div class="col-md-12">



                </div>

            </div>
        </div>
    </div>

{%endblock%}

ProyectoCultura/templates/usuarios/adm/autorizacionEvento.html
{%extends 'base/base_user.html'%}

    <!-- MENU SECTION END-->
{%block content%}

 <!-- MENU SECTION END-->
 <div class="content-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h4 class="page-head-line">Autorizar evento</h4>
                        <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="text-center">
        <img src="{{evento.imagen.url}}" class="avatar img-circle img-thumbnail" alt="avatar">
      </div>
    </div>
    <!-- edit form column -->
    <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
      <div class="alert alert-info alert-dismissable">
        <a class="panel-close close" data-dismiss="alert">×</a>
        <i class="fa fa-coffee"></i>
        <strong>Datos</strong>.
      </div>
      <h3>Evento</h3>
      <form class="form-horizontal" role="form" method="POST" enctype='multipart/form-data'>
      {%csrf_token%}
        <div class="form-group">
          <label class="col-lg-3 control-label">Titulo:</label>
          <div class="col-lg-8">
            <input class="form-control" value="{{evento.titulo}}" type="text" name="titulo" disabled>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label">Horario:</label>
          <div class="col-lg-8">
            <input class="form-control" value="{{evento.horario}}" type="text" name="horario" disabled>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-3 control-label">Direccion:</label>
          <div class="col-lg-8">
            <input class="form-control" value="{{evento.direccion}}" type="text" name="direccion" disabled>
          </div>
        </div>



<script type="text/javascript">
    $(".form_datetime").datetimepicker({
        format: "dd MM yyyy - hh:ii",
        autoclose: true,
        todayBtn: true,
        pickerPosition: "bottom-left"
    });
</script>

          <div class="form-group">
          <label class="col-lg-3 control-label">Descripcion:</label>
          <div class="col-lg-8">
            <textarea class="form-control" value="" type="text" name="descripcion" disabled>{{evento.descripcion}}
            </textarea >
          </div>
        </div>

        <div class="form-group">
          <label class="col-md-3 control-label"></label>
          <div class="col-md-8">
            <input class="btn btn-primary" value="Aceptar" type="submit">
            <span></span>
          </div>
        </div>
      </form>
    </div>

                </div>

            </div>
            <div class="row">
                <div class="col-md-12">



                </div>

            </div>
        </div>
    </div>


{%endblock%}

ProyectoCultura/templates/usuarios/adm/notificacion.html
{%extends 'base/base_user.html'%}

{%block content%}

    <section id="twitter">
        <div id="twitter-feed" class="carousel slide" data-interval="false">
            <div class="row">
            <div class="[ col-xs-12 col-sm-offset-2 col-sm-8 ]">
                

            <h4 class="page-head-line">Notificaciones de artistas</h4>         
            {% if artistas%}
            {% for noti in artistas%}
            <ul class="event-list">
                    <li>

                        <img alt="Independence Day" src="{{noti.artista.artista.imagen.url}}" />
                        <div class="info">
                            <h2 class="title">{{noti.artista.first_name}} {{noti.artista.last_name}}</h2>
                            <p class="desc">{{noti.artista.artista.descripcion}}</p>
                            <a href="{% url 'adm:autorizacion_artista' noti.artista.id%}"><button type="sumbit" class="btn btn-danger">Ver</button></a>
                        </div>                        
                    </li>
                </ul>

                </form>

            {%endfor%}

            {%else%}
            <h6>No hay notifiaciones de artistas</h6>
            <br>
            {%endif%}

            <h4 class="page-head-line">Notificaciones de eventos</h4>
            {% if eventos%}
            {% for noti in eventos%}
            <ul class="event-list">
                    <li>

                        <img alt="Independence Day" src="{{noti.evento.imagen.url}}" />
                        <div class="info">
                            <h2 class="title">{{noti.evento.titulo}}</h2>
                            <p class="desc">{{noti.evento.descripcion}}</p>
                            <a href="{% url 'adm:autorizacion_evento' noti.evento.id %}"><button type="sumbit" class="btn btn-danger">Ver</button></a>
                        </div>                        
                    </li>
                </ul>

                </form>

            {%endfor%}

            {%else%}
            <h5>No hay notificaciones de eventos</h5>
            {%endif%}

            </div>
        </div>
        </div>      
    </section>
    

{%endblock%}